default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    match(
      type: "appstore",
      app_identifier: [
        "com.ilks.fitpet",
        "com.ilks.fitpet.FitBadgerLiveActivity"
      ]
    )

    app_identifier = "com.ilks.fitpet"

    UI.user_error!("Please provide a version: fastlane beta version:1.0.1") unless options[:version]
    target_version = options[:version]

    UI.message("Target version: #{target_version}")

    target_build = latest_testflight_build_number(
      version: target_version,
      app_identifier: app_identifier,
      initial_build_number: 0
    ) + 1

    increment_version_number(
      version_number: target_version,
      xcodeproj: "FitBadger.xcodeproj"
    )

    increment_build_number(
      build_number: target_build.to_s,
      xcodeproj: "FitBadger.xcodeproj"
    )

    build_app(
      workspace: "FitBadger.xcworkspace",
      scheme: "FitBadger",
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      uses_non_exempt_encryption: false
    )
  end
end