export const resources = {
  tr: {
    translation: {
      welcome: "HOŞ GELDİN",
      appName: "Fit Badger!",
      getStarted: "Başla",
      defineGoals: "Hedeflerini belirleyelim",
      loseWeight: "Kilo Vermek",
      gainMuscle: "Kas Kazanmak",
      eatHealthier: "Sağlıklı Beslenmek",
      getMoreSleep: "Daha Fazla Uyku",
      drinkMoreWater: "Daha Çok Su İçmek",
      reduceStress: "Stresi Azaltmak",
      reduceAlcohol: "Alkolü Azaltmak",
      getMoreActive: "Daha Aktif Olmak",
      proceed: "Devam Et",
      identify: "Kendinizi nasıl tanımlarsınız?",
      male: "Erkek",
      female: "Kadın",
      nonBinary: "Diğer",
      yourAge: "Bize yaşınızı söyleyin",
      whyWeAsk: "Neden yaşınızı soruyoruz?",
      whyWeAskDescription:
        "Yaş, günlük kalori ve makro ihtiyaçlarınızı daha doğru hesaplamamıza yardımcı olur, bu da metabolizmanıza ve hedeflerinize uygun kişiselleştirilmiş beslenme önerileri sağlar.",
      getPhysical: "Fiziksel Özellikler",
      analyzing: "Profiliniz analiz ediliyor",
      calculating: "Optimal kalori alımı hesaplanıyor",
      finding: "Yemek planları aranıyor",
      optimizing: "Makro oranları optimize ediliyor",
      almostThere: "Neredeyse hazır",
      age: "Yaş",
      height: "Boy",
      weight: "Kilo",
      gender: "Cinsiyet",
      tabMeals: "Yemekler",
      tabHome: "Bugün",
      tabCook: "Pişir",
      tabChat: "AI Asistan",
      cookHeaderSubtitle: "Fikri planla, tarifi seç, adım adım pişir.",
      cookImmersiveTitle: "Cooking Badger",
      cookExit: "Çık",
      cookIntroTitle: "Bugün ne pişirmek istiyorsun?",
      cookIntroBody:
        "Bir malzeme ya da fikir yaz. Önce planı üç hızlı soruyla netleştireyim, gerekirse birkaç akıllı detay daha sorup sana iki güçlü tarif yönü hazırlayayım.",
      cookInputPrompt: "Temel fikrini yaz",
      cookInputPlaceholder: "Örn. tavuk, köfte, fasulye",
      cookStartPlanning: "Planı Başlat",
      cookLatestLabel: "Son tarif",
      cookQuestionTime: "Ne kadar vaktin var?",
      cookQuestionGoal: "Bugünkü hedefin ne?",
      cookQuestionServings: "Kaç porsiyon olsun?",
      cookQuestionMaxCalories: "Porsiyon başına en fazla kaç kalori olsun?",
      cookTime15: "15 dk",
      cookTime30: "30 dk",
      cookTime45: "45+ dk",
      cookGoalHighProtein: "Yüksek protein",
      cookGoalBalanced: "Dengeli",
      cookGoalLowCarb: "Düşük karbonhidrat",
      cookGoalBudgetFriendly: "Ekonomik",
      cookServing1: "1 kişilik",
      cookServing2: "2 kişilik",
      cookServing4: "4+ kişilik",
      cookCalories400: "400 kcal max",
      cookCalories600: "600 kcal max",
      cookCalories800: "800 kcal max",
      cookCalories1000: "1000 kcal max",
      cookCaloriesAny: "Fark etmez",
      cookPlanSeed: "Fikir",
      cookPlanTime: "Süre",
      cookPlanGoal: "Hedef",
      cookPlanServings: "Porsiyon",
      cookPlanCalories: "Kalori sınırı",
      cookPlanSummaryTitle: "Plan oluşuyor",
      cookAssistantLabel: "Cook ajanı",
      cookOnboardingTitle: "Cook ile tanış",
      cookOnboardingBody: "Malzeme veya fikir yaz, sana iki güçlü tarif yönü hazırlayalım.",
      cookOnboardingCardTitle: "Sana özel tarifler",
      cookOnboardingCardBody: "Cook, diyet tipini, kalori hedeflerini ve alerjilerini bilerek çalışır. Her öneri senin için tasarlanmıştır.",
      cookOnboardingCta: "Başlayalım",
      cookAllergenTitle: "Herhangi bir alerjin var mı?",
      cookAllergenBody: "Tarifler buna göre uyarlanacak.",
      cookAllergenNone: "Yok",
      cookAllergenGluten: "Gluten",
      cookAllergenDairy: "Süt Ürünleri",
      cookAllergenEggs: "Yumurta",
      cookAllergenNuts: "Kuruyemiş",
      cookAllergenPeanuts: "Fıstık",
      cookAllergenShellfish: "Kabuklu Deniz Ürünleri",
      cookAllergenFish: "Balık",
      cookAllergenSoy: "Soya",
      cookAllergenSesame: "Susam",
      cookAllergenContinue: "Devam Et",
      cookKitchenTitle: "Mutfak aletlerin neler?",
      cookKitchenBody: "Tarif önerileri buna göre uyarlanacak.",
      cookKitchenOven: "Fırın",
      cookKitchenAirFryer: "Air Fryer",
      cookKitchenStovetop: "Ocak",
      cookKitchenMicrowave: "Mikrodalga",
      cookKitchenBlender: "Blender",
      cookKitchenGrill: "Izgara",
      cookKitchenSlowCooker: "Slow Cooker",
      cookKitchenInstantPot: "Instant Pot",
      cookKitchenContinue: "Devam Et",
      cookQuestionProgress: "Soru {{current}} / {{total}}",
      cookClarifyProgress: "Detay {{current}} / {{total}}",
      cookFollowUpPlaceholder: "Biraz daha detay ver",
      cookContinue: "Devam Et",
      cookRecommended: "Önerilen",
      cookGeneratingCandidates: "Hazırlanıyor",
      cookBuildingRecipe: "Tarif ve görsel hazırlanıyor",
      cookChooseThis: "Bunu seç",
      cookFitLabel: "Uyum",
      cookStartCooking: "Pişirmeye Başla",
      cookModeLabel: "Pişirme modu",
      cookVariationTitle: "Tarifi değiştir",
      cookVariationSubtitle: "Bir varyasyona dokun, tarifi yeniden kurayım",
      cookVariationHint: "Dokun ve uygula",
      cookVariationRefreshing: "Yenileniyor",
      cookMetaPrep: "Hazırlık",
      cookMetaTime: "Süre",
      cookMetaServings: "Porsiyon",
      cookMetaLevel: "Seviye",
      cookDifficultyEasy: "Kolay",
      cookDifficultyMedium: "Orta",
      cookDifficultyHard: "Zor",
      cookPreviewMoreItems: "+{{count}} daha",
      cookIngredientsTitle: "Malzemeler",
      cookStepsTitle: "Adımlar",
      cookTipsTitle: "İpuçları",
      cookTimerLabel: "Zamanlayıcı",
      cookTimerReady: "Hazır",
      cookTimerRunning: "Çalışıyor",
      cookTimerDone: "Bitti",
      cookStepProgress: "Adım {{current}} / {{total}}",
      cookPrevious: "Geri",
      cookNextStep: "Sonraki adım",
      cookFinish: "Bitir",
      cookLogMealTitle: "Bu öğün kaydedilsin mi?",
      cookLogMealBody:
        "Bu tarifi pişirdin. Besin değerlerini analiz edip öğün olarak kaydedebilirim.",
      cookLogMealSkip: "Şimdi değil",
      cookLogMealConfirm: "Öğünü kaydet",
      cookLoggingMeal: "Pişirdiğin öğün analiz ediliyor",
      cookCompletedCount: "Tamamlanan adım: {{count}}",
      cookDiscardTitle: "Pişirme kapatılsın mı?",
      cookDiscardBody:
        "Şimdi çıkarsan bu tarif akışı ve seçilen ilerleme kaybolacak.",
      cookDiscardCancel: "Vazgeç",
      cookDiscardConfirm: "Çık",
      cookErrorTitle: "Cook şu an takıldı",
      cookErrorBody: "Tarif planı oluşturulamadı. Tekrar deneyelim.",
      cookTryAgain: "Baştan Başla",
      todaysMenu: "Bugünün Menüsü",
      noMealsLogged: "Henüz hiçbir öğün kaydedilmedi",
      loggedMeals: "Eklenmiş Öğünler",
      trackYourNutrition:
        "Gün boyunca öğünlerinizi kaydederek beslenmenizi takip edin",
      logYourFirstMeal: "Öğün Ekle",
      nutritionAssistant: "Beslenme Asistanı",
      startAConversation: "Bir sohbet başlat",
      askQuestion:
        "Beslenme, diyet planları veya yemek önerileri hakkında bir soru sor",
      typeYourMessage: "Mesajınızı yazın",
      settingsTitle: "Ayarlar",
      hi: "Merhaba",
      language: "Dil",
      aiTone: "AI Konuşma Tonu",
      toneHarsh: "Sert (varsayılan)",
      toneFriendly: "Dostça",
      toneFunny: "Eğlenceli",
      toneNerdy: "Bilimsel",
      toneSupportive: "Destekleyici",
      profile: "Profil",
      goals: "Hedefler",
      logout: "Çıkış Yap",
      saveChanges: "Değişiklikleri Kaydet",
      logAMeal: "Bir Öğün Kaydet",
      describeYourMeal: "Öğününüzü tarif edin",
      exampleMeal: "Örnek: Ispanaklı ve domatesli çırpılmış yumurta",
      breakfast: "Kahvaltı",
      lunch: "Öğle Yemeği",
      dinner: "Akşam Yemeği",
      snack: "Atıştırmalık",
      mealType: "Öğün Türü",
      addImage: "Resim Ekle",
      chooseImageSource: "Resim Kaynağını Seçin",
      camera: "Kamera",
      cameraPermissionRequired: "Yemek taramak icin kamera izni gerekiyor.",
      gallery: "Galeri",
      cancel: "İptal",
      carbs: "Karb.",
      proteins: "Protein",
      fats: "Yağ",
      calories: "Kalori",
      dailyTotal: "Günlük Toplam",
      analyzeMeal: "Öğünü Analiz Et",
      howWasMyLastMeal: "Son öğünüm nasıldı?",
      brutallyHonestFeedback: "Bana acımasız bir geri bildirim ver",
      howHealthyIsMyBmi: "BMI'ım ne kadar sağlıklı?",
      whatShouldIEatForDinner: "Akşam yemeğinde ne yemeliyim?",
      amIGettingEnoughProtein: "Yeterli protein alıyor muyum?",
      suggestAHealthySnack: "Sağlıklı bir atıştırmalık öner",
      instructions: "Talimatlar",
      ingredients: "Malzemeler",
      insights: "Tavsiyeler",
      mealAnalysis: "Yemek Analizi",
      nutritionScore: "Beslenme Puanı",
      excellent: "Mükemmel",
      good: "İyi",
      needsImprovement: "Geliştirilmesi Gerekiyor",
      macronutrients: "Makro Besinler",
      cal: "kal",
      delete: "Sil",
      edit: "Düzenle",
      scanAnother: "Başka Tara",
      deleteConfirmation: "Silme Onayı",
      deleteItemConfirmationMessage:
        "Bu öğeyi silmek istediğinizden emin misiniz?",
      error: "Hata",
      deleteFailed: "Silme işlemi başarısız oldu",
      score1: "Beslenme değil bu, biyolojik sabotaj.",
      score2: "Vücudun resmen istifa etmeye hazırlanıyor.",
      score3: "Kendini mi cezalandırıyorsun?",
      score4: "Vasat bile diyemiyorum.",
      score5: "Vasatın da alt sınırındasın.",
      score6: "Ne iyi ne kötü... İşte öyle bir şey.",
      score7: "Kendine biraz değer vermeye başlamışsın sanki.",
      score8: "Bugün sağlıklı kararlar krallığına adım attın.",
      score9: "Vücut şükrediyor, melekler alkışlıyor.",
      score10: "Mükemmel. Herkes seni konuşuyor. Bravo gerçekten.",
      // Friendly tone score explanations (Turkish)
      score1_friendly:
        "Bu öğün biraz sevgiye ihtiyaç duyuyor. Daha iyi seçenekler bulalım!",
      score2_friendly: "Geliştirilecek alan var. Yapabilirsin!",
      score3_friendly: "Zor bir tercih, ama yarın yeni bir gün.",
      score4_friendly: "En iyisi değil, ama her öğün bir öğrenme fırsatı.",
      score5_friendly:
        "Yarı yoldasın! Küçük değişiklikler büyük fark yaratabilir.",
      score6_friendly: "İyi bir çaba. Üzerine inşa etmeye devam et!",
      score7_friendly: "Güzel iş! İyi ilerleme kaydediyorsun.",
      score8_friendly: "Harika tercih! Vücudun sana teşekkür ediyor.",
      score9_friendly: "Mükemmel! Gerçekten başarıyorsun.",
      score10_friendly:
        "Olağanüstü! Sağlıklı beslenme tam olarak böyle görünür.",
      // Funny tone score explanations (Turkish)
      score1_funny: "Miden bile şikayet dilekçesi yazıyor.",
      score2_funny: "Diyetisyenin bir yerlerde bayıldı.",
      score3_funny:
        "Cesur strateji. Bakalım işe yarayacak mı. (Spoiler: hayır)",
      score4_funny: "Bu bir öğün mü yoksa yardım çığlığı mı?",
      score5_funny: "Eh işte. Yemek formunda bir pazartesi sabahı.",
      score6_funny:
        "Kabul edilebilir. Havaalanı yemeği gibi, ama biraz daha iyi.",
      score7_funny: "Bak sen! Sebzelerle yetişkin gibi davranıyorsun!",
      score8_funny: "Sen kimsin ve eski sen nerede?",
      score9_funny: "Vücudun şu an mini bir kutlama yapıyor.",
      score10_funny: "Şef öpücüğü! Gelecekteki sen sana beşlik çakıyor.",
      // Nerdy tone score explanations (Turkish)
      score1_nerdy:
        "Makro profil kritik seviyede. Acil beslenme kalibrasyonu önerilir.",
      score2_nerdy:
        "Besin yoğunluğu: minimum. Optimizasyon şiddetle tavsiye edilir.",
      score3_nerdy: "Bu örnekte suboptimal besin oranları tespit edildi.",
      score4_nerdy: "Veriler, baz çizgisinin altında besin değeri gösteriyor.",
      score5_nerdy: "Beslenme metrikleri medyan eşiğinde.",
      score6_nerdy:
        "Kabul edilebilir makro dengesi, optimizasyon alanı mevcut.",
      score7_nerdy: "İyi besin-kalori oranı gözlemlendi.",
      score8_nerdy: "Güçlü mikro besin profili. İyi kalibre edilmiş öğün.",
      score9_nerdy: "Neredeyse optimal makro dağılımı. Mükemmel veri noktası.",
      score10_nerdy:
        "Zirve beslenme verimliliği sağlandı. Ders kitabı uygulaması.",
      // Supportive tone score explanations (Turkish)
      score1_supportive:
        "Her adım ilerleme demek. Bir sonraki öğünü daha iyi planlayalım.",
      score2_supportive: "Sorun değil. Önemli olan takip edip öğrenmen.",
      score3_supportive: "Farkındasın ve bu değişimin ilk adımı.",
      score4_supportive: "İdeal değil, ama dikkat ediyorsun. Bu önemli.",
      score5_supportive: "Doğru yoldasın. Devam et!",
      score6_supportive: "Sağlam çaba! Her öğün gelişme şansı.",
      score7_supportive: "İyi gidiyorsun! Bu tercihle gurur duy.",
      score8_supportive: "Harika! Bu gerçek bir sağlık taahhüdü gösteriyor.",
      score9_supportive: "Müthiş iş! Bundan dolayı harika hissetmelisin.",
      score10_supportive: "İnanılmaz! Kendine harika bakıyorsun.",
      dailySummary: "Günün Özeti",
      averageScore: "Ort. Puan",
      globalError: "Bir hata oluştu",
      globalErrorDescription: "Lütfen daha sonra tekrar deneyin",
      selectLanguage: "Dil Seçin",
      dietRegular: "Standart",
      dietVegetarian: "Vejetaryen",
      dietVegan: "Vegan",
      dietPescatarian: "Pesketaryen",
      dietFlexitarian: "Esnek Vegan",
      dietKeto: "Ketojenik",
      dietLowCarb: "Düşük Karbonhidrat",
      dietIntermittentFasting: "Aralıklı Oruç",
      dietPaleo: "Paleo",
      dietWestern: "Batı Tipi",
      dietTypesTitle: "Beslenme Düzenin",
      save: "Kaydet",
      adjustNutritionGoals: "Beslenme Hedefleri",
      logoutConfirmation: "Çıkış Yap",
      logoutConfirmationMessage: "Çıkış yapmak istediğinizden emin misiniz?",
      deleteAccountConfirmation: "Hesabı Sil",
      deleteAccountConfirmationMessage:
        "Hesabınızı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
      appearance: "Görünüm",
      darkMode: "Koyu Mod",
      welcomeExplanation: "Öğünlerinizi takip edin ve hedeflerinize ulaşın.",
      existingUser: "Zaten hesabın var mı?",
      login: "Giriş Yap",
      preparationTime: "Hazırlama Süresi",
      signUpTitle: "Fit Badger'a Katıl!",
      signUpSubtitle: "Öğünleri takip et ve hedeflerine ulaş.",
      signUpWithGoogle: "Google ile kayıt ol",
      signUpWithApple: "Apple ile kayıt ol",
      signUpWithEmail: "E-posta ile kayıt ol",
      email: "E-posta",
      password: "Şifre",
      confirmPassword: "Şifreyi Onayla",
      enterEmail: "E-posta adresinizi girin",
      enterPassword: "Şifrenizi girin",
      confirmYourPassword: "Şifrenizi onaylayın",
      signUp: "Kayıt Ol",
      alreadyHaveAccount: "Zaten hesabın var mı?",
      logIn: "Giriş Yap",
      termsAgreement: "Devam ederek",
      termsOfService: "Kullanım Şartları",
      and: "ve",
      privacyPolicy: "Gizlilik Politikası",
      termsAgreementEnd: "kabul etmiş olursunuz.",
      invalidEmail: "Geçersiz e-posta adresi",
      passwordsDoNotMatch: "Şifreler eşleşmiyor",
      loginTitle: "Tekrar Hoş Geldin!",
      loginSubtitle: "Hesabına giriş yap.",
      loginWithGoogle: "Google ile giriş yap",
      loginWithApple: "Apple ile giriş yap",
      loginWithEmail: "E-posta ile giriş yap",
      noAccountYet: "Hesabın yok mu?",
      globalErrorMessage: "Lütfen daha sonra tekrar deneyin",
      signUpBanner: "Kayıt olarak profilini tamamla.",
      caloriesAndProtein: "Kalori ve Protein",
      setYourDailyNutritionGoals: "Günlük besin hedeflerinizi belirleyin",
      nutritionGoals: "Beslenme Hedefleri",
      dailyGoal: "GÜNLÜK HEDEF",
      proteinDistribution: "Protein Dağılımı",
      total: "Toplam",
      other: "Diğer",
      otherCarbsFat: "Diğer (Karb. & Yağ)",
      consumed: "Alınan",
      remaining: "Kalan",
      goal: "Hedef",
      score: "Puan",
      over: "Aşıldı",
      tapToAddMeal: "Öğün eklemek için dokun",
      analyzingMeal: "Öğününüz analiz ediliyor",
      readyToAnalyze: "Analiz İçin Hazır",
      selectMealTypeAndAnalyze: "Öğün türünü seçin ve analiz edin",
      calculatingNutrients: "Besin değerleri hesaplanıyor",
      evaluatingScore: "Puan değerlendiriliyor",
      almostReady: "Neredeyse hazır",
      // Carousel motivational messages
      carouselTitle1: "Harika Bir Başlangıç!",
      carouselMessage1:
        "{{age}} yaşında sağlıklı bir yaşam yolculuğuna çıkıyorsunuz. Her adım önemli!",
      carouselTitle2: "Mükemmel Fizik!",
      carouselMessage2:
        "{{height}} cm boyunuzla ideal kilonuza ulaşmak artık çok kolay olacak.",
      carouselTitle3: "Hedefler Belirlendi!",
      carouselMessage3:
        "Kişiselleştirilmiş planınız hazırlanıyor. Başarı sizin için kaçınılmaz!",
      carouselTitle4: "Her Şey Hazır!",
      carouselMessage4:
        "Sağlıklı yaşam yolculuğunuz başlamak üzere. Hazır mısınız?",
      success: "Başarılı",
      successMessage: "Değişiklikleriniz kaydedildi",
      validationError: "Hata",
      enterValidNumbers: "Lütfen geçerli bir sayı girin",
      tabSettings: "Ayarlar",
      // Notification strings
      notifications: "Bildirimler",
      enableNotifications: "Bildirimleri Etkinleştir",
      mealReminders: "Öğün Hatırlatıcıları",
      mealTimeTitle: "Öğün Saatlerini Ayarla",
      mealTimeDescription:
        "Öğün hatırlatıcıları almak için yaklaşık öğün saatlerinizi ayarlayın.",
      reminderTime: "Hatırlatma saati",
      breakfastReminder: "Kahvaltı Zamanı! 🍳",
      lunchReminder: "Öğle Yemeği Zamanı! 🥗",
      dinnerReminder: "Akşam Yemeği Zamanı! 🍽️",
      mealReminderBody: "Öğününüzü kaydetmeyi unutmayın!",
      dinnerReminderInfo:
        "Başlangıçta sadece akşam yemeği hatırlatıcısı etkinleştirilecek. Daha fazla hatırlatıcı daha sonra açılabilir.",
      notificationPermissionDenied: "Bildirim İzni Reddedildi",
      notificationPermissionDeniedMessage:
        "Lütfen hatırlatıcılar için ayarlardan bildirim iznini etkinleştirin.",
      featureLocked: "Özellik Kilitli",
      featureLockedMessage: "Bu özellik henüz mevcut değil.",
      unlockBreakfastLunch:
        "Bu hatırlatıcıyı açmak için {{days}} gün daha öğün kaydedin.",
      progressiveUnlockInfo:
        "Kahvaltı ve öğle yemeği hatırlatıcılarının kilidini açmak için {{days}} gün daha öğün kaydedin.",
      unlockAllRemindersTitle: "Tüm Hatırlatıcıları Aç!",
      unlockAllRemindersMessage:
        "Tebrikler! 2 farklı günde öğün kaydettiniz. Şimdi kahvaltı ve öğle yemeği hatırlatıcılarını da etkinleştirebilirsiniz.",
      enableNow: "Şimdi Etkinleştir",
      maybeLater: "Belki Sonra",
      skip: "Atla",
    },
  },

  en: {
    translation: {
      welcome: "WELCOME TO",
      appName: "Fit Badger!",
      getStarted: "Get Started",
      defineGoals: "First, let's define your goals",
      loseWeight: "Lose Weight",
      gainMuscle: "Gain Muscle",
      eatHealthier: "Eat Healthier",
      getMoreSleep: "Get More Sleep",
      drinkMoreWater: "Drink More Water",
      reduceStress: "Reduce Stress",
      reduceAlcohol: "Reduce Alcohol",
      getMoreActive: "Get More Active",
      proceed: "Proceed",
      identify: "How do you identify?",
      male: "Male",
      female: "Female",
      nonBinary: "Non-binary",
      yourAge: "Tell us your age",
      whyWeAsk: "Why do we ask your age?",
      whyWeAskDescription:
        "Age helps us calculate your daily calorie and macro needs more accurately, so recommendations actually fit your metabolism and goals.",
      getPhysical: "Physical Details",
      analyzing: "Analyzing your profile",
      calculating: "Calculating optimal calorie intake",
      finding: "Finding suitable meal plans",
      optimizing: "Optimizing macro ratios",
      almostThere: "Almost there",
      age: "Age",
      height: "Height",
      weight: "Weight",
      gender: "Gender",
      tabMeals: "Meals",
      tabHome: "Today",
      tabCook: "Cook",
      tabChat: "AI Coach",
      cookHeaderSubtitle: "Plan the idea, pick a recipe, cook it step by step.",
      cookImmersiveTitle: "Cooking Badger",
      cookExit: "Quit",
      cookIntroTitle: "What are you thinking of cooking?",
      cookIntroBody:
        "Start with an ingredient or rough idea. I will tighten it up with three quick questions, then ask for a few smart details if needed before giving you two strong directions.",
      cookInputPrompt: "Start with the core idea",
      cookInputPlaceholder: "Ex. chicken, quick pasta, lentils",
      cookStartPlanning: "Start Planning",
      cookLatestLabel: "Latest",
      cookQuestionTime: "How much time do you have?",
      cookQuestionGoal: "What's your goal today?",
      cookQuestionServings: "How many servings?",
      cookQuestionMaxCalories: "What's the max calories per serving?",
      cookTime15: "15 min",
      cookTime30: "30 min",
      cookTime45: "45+ min",
      cookGoalHighProtein: "High Protein",
      cookGoalBalanced: "Balanced",
      cookGoalLowCarb: "Low Carb",
      cookGoalBudgetFriendly: "Budget Friendly",
      cookServing1: "1 serving",
      cookServing2: "2 servings",
      cookServing4: "4+ servings",
      cookCalories400: "400 kcal max",
      cookCalories600: "600 kcal max",
      cookCalories800: "800 kcal max",
      cookCalories1000: "1000 kcal max",
      cookCaloriesAny: "No limit",
      cookPlanSeed: "Idea",
      cookPlanTime: "Time",
      cookPlanGoal: "Goal",
      cookPlanServings: "Servings",
      cookPlanCalories: "Calorie cap",
      cookPlanSummaryTitle: "Building your plan",
      cookAssistantLabel: "Cook agent",
      cookOnboardingTitle: "Meet Cook",
      cookOnboardingBody: "Drop an ingredient or rough idea and get two strong recipe directions built around your goals.",
      cookOnboardingCardTitle: "Recipes built for you",
      cookOnboardingCardBody: "Cook knows your diet type, calorie targets, and allergens. Every suggestion is tailored to you.",
      cookOnboardingCta: "Get Started",
      cookAllergenTitle: "Any allergens?",
      cookAllergenBody: "Recipes will be adapted accordingly.",
      cookAllergenNone: "None",
      cookAllergenGluten: "Gluten",
      cookAllergenDairy: "Dairy",
      cookAllergenEggs: "Eggs",
      cookAllergenNuts: "Tree Nuts",
      cookAllergenPeanuts: "Peanuts",
      cookAllergenShellfish: "Shellfish",
      cookAllergenFish: "Fish",
      cookAllergenSoy: "Soy",
      cookAllergenSesame: "Sesame",
      cookAllergenContinue: "Continue",
      cookKitchenTitle: "What's in your kitchen?",
      cookKitchenBody: "Recipe suggestions will be adapted accordingly.",
      cookKitchenOven: "Oven",
      cookKitchenAirFryer: "Air Fryer",
      cookKitchenStovetop: "Stovetop",
      cookKitchenMicrowave: "Microwave",
      cookKitchenBlender: "Blender",
      cookKitchenGrill: "Grill",
      cookKitchenSlowCooker: "Slow Cooker",
      cookKitchenInstantPot: "Instant Pot",
      cookKitchenContinue: "Continue",
      cookQuestionProgress: "Question {{current}} / {{total}}",
      cookClarifyProgress: "Detail {{current}} / {{total}}",
      cookFollowUpPlaceholder: "Add one more detail",
      cookContinue: "Continue",
      cookRecommended: "Recommended",
      cookGeneratingCandidates: "Preparing",
      cookBuildingRecipe: "Building recipe and generating image",
      cookChooseThis: "Choose this one",
      cookFitLabel: "Fit",
      cookStartCooking: "Start Cooking",
      cookModeLabel: "Cook mode",
      cookVariationTitle: "Change this recipe",
      cookVariationSubtitle: "Tap a variation and I will rebuild it",
      cookVariationHint: "Tap to apply",
      cookVariationRefreshing: "Refreshing",
      cookMetaPrep: "Prep",
      cookMetaTime: "Time",
      cookMetaServings: "Servings",
      cookMetaLevel: "Level",
      cookDifficultyEasy: "Easy",
      cookDifficultyMedium: "Medium",
      cookDifficultyHard: "Hard",
      cookPreviewMoreItems: "+{{count}} more",
      cookIngredientsTitle: "Ingredients",
      cookStepsTitle: "Steps",
      cookTipsTitle: "Tips",
      cookTimerLabel: "Timer",
      cookTimerReady: "Ready",
      cookTimerRunning: "Running",
      cookTimerDone: "Done",
      cookStepProgress: "Step {{current}} of {{total}}",
      cookPrevious: "Previous",
      cookNextStep: "Next step",
      cookFinish: "Finish",
      cookLogMealTitle: "Log this meal?",
      cookLogMealBody:
        "You finished cooking this recipe. I can analyze it and log it as a meal.",
      cookLogMealSkip: "Not now",
      cookLogMealConfirm: "Log meal",
      cookLoggingMeal: "Analyzing your cooked meal",
      cookCompletedCount: "Completed steps: {{count}}",
      cookDiscardTitle: "Leave cooking?",
      cookDiscardBody:
        "If you exit now, this recipe flow and your current progress will be discarded.",
      cookDiscardCancel: "Cancel",
      cookDiscardConfirm: "Leave",
      cookErrorTitle: "Cook hit a snag",
      cookErrorBody:
        "I couldn't build that recipe plan right now. Let's try again.",
      cookTryAgain: "Start Over",
      todaysMenu: "Today's Menu",
      noMealsLogged: "No meals logged yet",
      loggedMeals: "Logged Meals",
      trackYourNutrition:
        "Track your nutrition by logging meals throughout the day",
      logYourFirstMeal: "Add a Meal",
      nutritionAssistant: "Nutrition Coach",
      startAConversation: "Start a conversation",
      askQuestion:
        "Ask a question about nutrition, diet plans, or meal suggestions",
      typeYourMessage: "Type your message",
      settingsTitle: "Settings",
      hi: "Hi",
      language: "Language",
      aiTone: "AI speaking tone",
      toneHarsh: "Harsh (default)",
      toneFriendly: "Friendly",
      toneFunny: "Funny",
      toneNerdy: "Nerdy",
      toneSupportive: "Supportive",
      profile: "Profile",
      goals: "Goals",
      logout: "Log Out",
      saveChanges: "Save Changes",
      logAMeal: "Log a Meal",
      describeYourMeal: "Describe your meal",
      exampleMeal: "Example: Scrambled eggs with spinach and tomatoes",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
      mealType: "Meal Type",
      addImage: "Add Image",
      chooseImageSource: "Choose Image Source",
      camera: "Camera",
      cameraPermissionRequired: "Camera permission is required to scan a meal.",
      gallery: "Gallery",
      cancel: "Cancel",
      carbs: "Carbs",
      proteins: "Proteins",
      fats: "Fats",
      calories: "Calories",
      dailyTotal: "Daily Total",
      analyzeMeal: "Analyze Meal",
      howWasMyLastMeal: "How was my last meal?",
      brutallyHonestFeedback: "Give me brutally honest feedback",
      howHealthyIsMyBmi: "How healthy is my BMI?",
      whatShouldIEatForDinner: "What should I eat for dinner?",
      amIGettingEnoughProtein: "Am I getting enough protein?",
      suggestAHealthySnack: "Suggest a healthy snack",
      instructions: "Instructions",
      ingredients: "Ingredients",
      insights: "Insights",
      mealAnalysis: "Meal Analysis",
      nutritionScore: "Nutrition Score",
      excellent: "Excellent",
      good: "Good",
      needsImprovement: "Needs Improvement",
      macronutrients: "Macronutrients",
      cal: "cal",
      delete: "Delete",
      edit: "Edit",
      scanAnother: "Scan Another",
      deleteConfirmation: "Delete Confirmation",
      deleteItemConfirmationMessage:
        "Are you sure you want to delete this item?",
      error: "Error",
      deleteFailed: "Delete failed",
      score1: "This isn't nutrition. It's sabotage.",
      score2: "Your body is drafting a resignation letter.",
      score3: "Punishing yourself again?",
      score4: "Calling this food is generous.",
      score5: "Below average. Impressively so.",
      score6: "Not great. Not terrible.",
      score7: "Looks like you almost care.",
      score8: "Good choices today. Shocking.",
      score9: "Your body approves. Rare event.",
      score10: "Perfect. No notes.",
      // Friendly tone score explanations
      score1_friendly: "This meal needs some love. Let's find better options!",
      score2_friendly: "Room for improvement here. You've got this!",
      score3_friendly: "A challenging choice, but tomorrow is a new day.",
      score4_friendly: "Not your best, but every meal is a learning moment.",
      score5_friendly: "Halfway there! Small tweaks can make a big difference.",
      score6_friendly: "A decent effort. Keep building on it!",
      score7_friendly: "Nice work! You're making good progress.",
      score8_friendly: "Great choice! Your body thanks you.",
      score9_friendly: "Excellent! You're really nailing this.",
      score10_friendly: "Outstanding! This is exactly what healthy looks like.",
      // Funny tone score explanations
      score1_funny: "Even your stomach is filing a complaint.",
      score2_funny: "Your nutritionist just fainted somewhere.",
      score3_funny: "Bold strategy. Let's see if it pays off. (Spoiler: no)",
      score4_funny: "Is this a meal or a cry for help?",
      score5_funny: "Meh. Like a Monday morning in food form.",
      score6_funny: "Acceptable. Like airport food, but slightly better.",
      score7_funny: "Look at you, adulting with vegetables!",
      score8_funny: "Who are you and what did you do with the old you?",
      score9_funny: "Your body is throwing a tiny party right now.",
      score10_funny: "Chef's kiss! Your future self is high-fiving you.",
      // Nerdy tone score explanations
      score1_nerdy:
        "Macro profile critical. Immediate dietary recalibration advised.",
      score2_nerdy:
        "Nutrient density: minimal. Optimization strongly recommended.",
      score3_nerdy: "Suboptimal nutrient ratios detected in this sample.",
      score4_nerdy: "Data suggests below-baseline nutritional value.",
      score5_nerdy: "Nutritional metrics at median threshold.",
      score6_nerdy: "Acceptable macro balance with room for optimization.",
      score7_nerdy: "Good nutrient-to-calorie ratio observed.",
      score8_nerdy: "Strong micronutrient profile. Well-calibrated meal.",
      score9_nerdy: "Near-optimal macro distribution. Excellent data point.",
      score10_nerdy:
        "Peak nutritional efficiency achieved. Textbook execution.",
      // Supportive tone score explanations
      score1_supportive:
        "Every step is progress. Let's plan a better next meal.",
      score2_supportive:
        "It's okay. What matters is you're tracking and learning.",
      score3_supportive: "You're aware, and that's the first step to change.",
      score4_supportive: "Not ideal, but you're paying attention. That counts.",
      score5_supportive: "You're on the right path. Keep going!",
      score6_supportive: "Solid effort! Each meal is a chance to improve.",
      score7_supportive: "You're doing well! Be proud of this choice.",
      score8_supportive:
        "Wonderful! This shows real commitment to your health.",
      score9_supportive: "Amazing work! You should feel great about this.",
      score10_supportive: "Incredible! You're taking amazing care of yourself.",
      dailySummary: "Daily Summary",
      averageScore: "Avg. Score",
      globalError: "An error occurred",
      globalErrorDescription: "Please try again later",
      selectLanguage: "Select Language",
      dietRegular: "Regular",
      dietVegetarian: "Vegetarian",
      dietVegan: "Vegan",
      dietPescatarian: "Pescatarian",
      dietFlexitarian: "Flexitarian",
      dietKeto: "Keto",
      dietLowCarb: "Low Carb",
      dietIntermittentFasting: "Intermittent Fasting",
      dietPaleo: "Paleo",
      dietWestern: "Western",
      dietTypesTitle: "Your Diet Type",
      save: "Save",
      adjustNutritionGoals: "Adjust Nutrition Goals",
      logoutConfirmation: "Log Out",
      logoutConfirmationMessage: "Are you sure you want to log out?",
      deleteAccountConfirmation: "Delete Account",
      deleteAccountConfirmationMessage:
        "Are you sure you want to delete your account? This action is irreversible.",
      appearance: "Appearance",
      darkMode: "Dark Mode",
      welcomeExplanation: "Meal tracking and goals. No sugarcoating.",
      existingUser: "Already have an account?",
      login: "Log In",
      preparationTime: "Prep Time",
      signUpTitle: "Join Fit Badger!",
      signUpSubtitle: "Track meals and achieve your goals.",
      signUpWithGoogle: "Sign up with Google",
      signUpWithApple: "Sign up with Apple",
      signUpWithEmail: "Sign up with Email",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      enterEmail: "Enter your email",
      enterPassword: "Enter your password",
      confirmYourPassword: "Confirm your password",
      signUp: "Sign Up",
      alreadyHaveAccount: "Already have an account?",
      logIn: "Log In",
      termsAgreement: "By continuing, you agree to our",
      termsOfService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      termsAgreementEnd: ".",
      invalidEmail: "Invalid email address",
      passwordsDoNotMatch: "Passwords do not match",
      loginTitle: "Welcome Back!",
      loginSubtitle: "Log in to your account.",
      loginWithGoogle: "Log in with Google",
      loginWithApple: "Log in with Apple",
      loginWithEmail: "Log in with Email",
      noAccountYet: "Don't have an account?",
      globalErrorMessage: "Please try again later",
      signUpBanner: "Sign up to complete your profile.",
      caloriesAndProtein: "Calories and Protein",
      setYourDailyNutritionGoals: "Set your daily nutrition goals",
      nutritionGoals: "Nutrition Goals",
      dailyGoal: "DAILY GOAL",
      proteinDistribution: "Protein Distribution",
      total: "Total",
      other: "Other",
      otherCarbsFat: "Other (Carbs & Fat)",
      consumed: "Consumed",
      remaining: "Remaining",
      goal: "Goal",
      score: "Score",
      over: "Over",
      tapToAddMeal: "Tap to add a meal",
      analyzingMeal: "Analyzing your meal",
      readyToAnalyze: "Ready to Analyze",
      selectMealTypeAndAnalyze: "Select meal type and analyze",
      calculatingNutrients: "Calculating nutrients",
      evaluatingScore: "Evaluating score",
      almostReady: "Almost ready",
      // Carousel motivational messages
      carouselTitle1: "Great Start!",
      carouselMessage1:
        "At {{age}} years old, you're embarking on a healthy lifestyle journey. Every step counts!",
      carouselTitle2: "Perfect Physique!",
      carouselMessage2:
        "With your {{height}} cm height, reaching your ideal weight will be easier than ever.",
      carouselTitle3: "Goals Set!",
      carouselMessage3:
        "Your personalized plan is being prepared. Success is inevitable for you!",
      carouselTitle4: "All Ready!",
      carouselMessage4:
        "Your healthy lifestyle journey is about to begin. Are you ready?",
      success: "Success",
      successMessage: "Changes saved successfully",
      validationError: "Error",
      enterValidNumbers: "Please enter a valid number",
      tabSettings: "Settings",
      // Notification strings
      notifications: "Notifications",
      enableNotifications: "Enable Notifications",
      mealReminders: "Meal Reminders",
      mealTimeTitle: "Set Meal Times",
      mealTimeDescription:
        "Set your approximate meal times to receive meal reminders.",
      reminderTime: "Reminder time",
      breakfastReminder: "Breakfast Time! 🍳",
      lunchReminder: "Lunch Time! 🥗",
      dinnerReminder: "Dinner Time! 🍽️",
      mealReminderBody: "Don't forget to log your meal!",
      dinnerReminderInfo:
        "Only dinner reminder will be enabled initially. More reminders can be unlocked later.",
      notificationPermissionDenied: "Notification Permission Denied",
      notificationPermissionDeniedMessage:
        "Please enable notification permission in settings for reminders.",
      featureLocked: "Feature Locked",
      featureLockedMessage: "This feature is not available yet.",
      unlockBreakfastLunch:
        "Log meals for {{days}} more day(s) to unlock this reminder.",
      progressiveUnlockInfo:
        "Log meals for {{days}} more day(s) to unlock breakfast and lunch reminders.",
      unlockAllRemindersTitle: "Unlock All Reminders!",
      unlockAllRemindersMessage:
        "Congratulations! You've logged meals on 2 different days. You can now enable breakfast and lunch reminders too.",
      enableNow: "Enable Now",
      maybeLater: "Maybe Later",
      skip: "Skip",
    },
  },
};
