export const resources = {
  tr: {
    translation: {
      welcome: "Hoş geldin",
      appName: "FitPet!",
      getStarted: "Başla",
      defineGoals: "Hedeflerini belirleyelim",
      loseWeight: "Kilo Vermek",
      gainMuscle: "Kas Kazanmak",
      eatHeathier: "Sağlıklı Beslenmek",
      getMoreSleep: "Daha Fazla Uyku",
      drinkMoreWater: "Daha Çok Su İçmek",
      reduceStress: "Stresi Azaltmak",
      reduceAlcohol: "Alkolü Azaltmak",
      getMoreActive: "Daha Aktif Olmak",
      proceed: "Devam Et",
      identify: "Kendinizi nasıl tanımlarsınız?",
      male: "Erkek",
      female: "Kadın",
      nonBinary: "Diğer",
      yourAge: "Yaşınızı söyleyin",
      whyWeAsk: "Neden yaşınızı soruyoruz?",
      whyWeAskDescription:
        "Yaş, günlük kalori ve makro ihtiyaçlarınızı daha doğru hesaplamamıza yardımcı olur, bu da metabolizmanıza ve hedeflerinize uygun kişiselleştirilmiş beslenme önerileri sağlar.",
      getPhysical: "Fiziksel Özellikler",
      analyzing: "Profiliniz analiz ediliyor...",
      calculating: "Optimal kalori alımı hesaplanıyor...",
      finding: "Size uygun yemek planları aranıyor...",
      optimizing: "Makro oranları optimize ediliyor...",
      almostThere: "Neredeyse hazır...",
      age: "Yaş",
      height: "Boy",
      weight: "Kilo",
      gender: "Cinsiyet",
      tabMeals: "Yemekler",
      tabHome: "Ana Sayfa",
      tabChat: "AI Asistan",
      todaysMenu: "Bugünün Menüsü",
      noMealsLogged: "Henüz hiçbir öğün kaydedilmedi",
      loggedMeals: "Eklenmiş Öğünler",
      trackYourNutrition:
        "Gün boyunca öğünlerinizi kaydederek beslenmenizi takip edin",
      logYourFirstMeal: "İlk öğününüzü ekleyin",
      nutritionAssistant: "Beslenme Asistanı",
      startAConversation: "Bir sohbet başlat",
      askQuestion:
        "Beslenme, diyet planları veya yemek önerileri hakkında bir soru sor",
      typeYourMessage: "Mesajınızı yazın",
      settingsTitle: "Ayarlar",
      language: "Dil",
      profile: "Profil",
      goals: "Hedefler",
      logout: "Çıkış Yap",
      saveChanges: "Değişiklikleri Kaydet",
      logAMeal: "Bir Öğün Kaydet",
      describeYourMeal: "Öğününüzü tarif edin",
      exampleMeal: "Örnek: Ispanaklı ve domatesli çırpılmış yumurta",
      breakfast: "Kahvaltı",
      lunch: "Öğle Yemeği",
      dinner: "Akşam Yemeği",
      snack: "Atıştırmalık",
      mealType: "Öğün Türü",
      addImage: "Resim Ekle",
      chooseImageSource: "Resim Kaynağını Seçin",
      camera: "Kamera",
      gallery: "Galeri",
      cancel: "İptal",
      carbs: "Karbonhidrat",
      proteins: "Protein",
      fats: "Yağ",
      calories: "Kalori",
      dailyTotal: "Günlük Toplam",
      analyzeMeal: "Öğünü Analiz Et",
      howWasMyLastMeal: "Son öğünüm nasıldı?",
      brutallyHonestFeedback: "Bana acımasız bir geri bildirim ver",
      instructions: "Talimatlar",
      ingredients: "Malzemeler",
      insights: "Tavsiyeler",
      mealAnalysis: "Yemek Analizi",
      nutritionScore: "Beslenme Puanı",
      excellent: "Mükemmel",
      good: "İyi",
      needsImprovement: "Geliştirilmesi Gerekiyor",
      macronutrients: "Makro Besinler",
      cal: "kal",
      delete: "Sil",
      deleteConfirmation: "Silme Onayı",
      deleteItemConfirmationMessage:
        "Bu öğeyi silmek istediğinizden emin misiniz?",
      error: "Hata",
      deleteFailed: "Silme işlemi başarısız oldu",
      score1: "Beslenme değil bu, biyolojik sabotaj.",
      score2: "Vücudun resmen istifa etmeye hazırlanıyor.",
      score3: "Kendini mi cezalandırıyorsun?",
      score4: "Vasat bile diyemiyorum.",
      score5: "Vasatın da alt sınırındasın.",
      score6: "Ne iyi ne kötü... İşte öyle bir şey.",
      score7: "Kendine biraz değer vermeye başlamışsın sanki.",
      score8: "Bugün sağlıklı kararlar krallığına adım attın.",
      score9: "Vücut şükrediyor, melekler alkışlıyor.",
      score10: "Mükemmel. Herkes seni konuşuyor. Bravo gerçekten.",
      dailySummary: "Günün Özeti",
      averageScore: "Ort. Puan",
      globalError: "Bir hata oluştu",
      globalErrorDescription: "Lütfen daha sonra tekrar deneyin",
      selectLanguage: "Dil Seçin",
      dietRegular: "Standart",
      dietVegetarian: "Vejetaryen",
      dietVegan: "Vegan",
      dietPescatarian: "Pesketaryen",
      dietFlexitarian: "Esnek Vegan",
      dietKeto: "Ketojenik",
      dietLowCarb: "Düşük Karbonhidrat",
      dietIntermittentFasting: "Aralıklı Oruç",
      dietPaleo: "Paleo",
      dietWestern: "Batı Tipi",
      dietTypesTitle: "Beslenme Düzenin",
      save: "Kaydet",
    },
  },
  en: {
    translation: {
      welcome: "Welcome to",
      appName: "FitPet!",
      getStarted: "Get Started",
      defineGoals: "First, let's define your goals",
      loseWeight: "Lose Weight",
      gainMuscle: "Gain Muscle",
      eatHeathier: "Eat Healthier",
      getMoreSleep: "Get More Sleep",
      drinkMoreWater: "Drink More Water",
      reduceStress: "Reduce Stress",
      reduceAlcohol: "Reduce Alcohol",
      getMoreActive: "Get More Active",
      proceed: "Proceed",
      identify: "How do you identify?",
      male: "male",
      female: "female",
      nonBinary: "non-binary",
      yourAge: "Tell us your age",
      whyWeAsk: "Why we ask for your age?",
      whyWeAskDescription:
        "Age helps us calculate your daily calorie and macro needs more accurately, ensuring personalized nutrition recommendations that fit your metabolism and goals.",
      getPhysical: "Let's get physical",
      analyzing: "Analyzing your profile...",
      calculating: "Calculating optimal calorie intake...",
      finding: "Finding the perfect meal plans...",
      optimizing: "Optimizing macro ratios...",
      almostThere: "Almost there...",
      age: "Age",
      height: "Height",
      weight: "Weight",
      gender: "Gender",
      tabMeals: "Meals",
      tabHome: "Home",
      tabChat: "AI Assistant",
      todaysMenu: "Today's Menu",
      noMealsLogged: "No meals logged yet",
      loggedMeals: "Logged Meals",
      trackYourNutrition:
        "Track your nutrition by logging your meals throughout the day",
      logYourFirstMeal: "Log your first meal",
      nutritionAssistant: "Nutrition Assistant",
      startAConversation: "Start a conversation",
      askQuestion:
        "Ask a questions about nutrition, diet plans or meal suggestions",
      typeYourMessage: "Type your message",
      settingsTitle: "Settings",
      language: "Language",
      profile: "Profile",
      goals: "Goals",
      logout: "Logout",
      saveChanges: "Save Changes",
      logAMeal: "Log a Meal",
      describeYourMeal: "Describe your meal",
      exampleMeal: "Example: Scrambled eggs with spinach and tomatoes",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
      mealType: "Meal Type",
      addImage: "Add Image",
      chooseImageSource: "Choose Image Source",
      camera: "Camera",
      gallery: "Gallery",
      cancel: "Cancel",
      carbs: "Carbs",
      proteins: "Proteins",
      fats: "Fats",
      calories: "Calories",
      dailyTotal: "Daily Total",
      analyzeMeal: "Analyze Meal",
      howWasMyLastMeal: "How was my last meal?",
      brutallyHonestFeedback: "Give me a brutally honest feedback",
      instructions: "Instructions",
      ingredients: "Ingredients",
      insights: "Insights",
      mealAnalysis: "Meal Analysis",
      nutritionScore: "Nutrition Score",
      excellent: "Excellent",
      good: "Good",
      needsImprovement: "Needs Improvement",
      macronutrients: "Macronutrients",
      cal: "cal",
      delete: "Delete",
      deleteConfirmation: "Delete Confirmation",
      deleteItemConfirmationMessage:
        "Are you sure you want to delete this item?",
      error: "Error",
      deleteFailed: "Delete operation failed",
      score1: "Absolute Dietary Disaster",
      score2: "Your Body Is Filing Complaints",
      score3: "Did You Lose a Bet?",
      score4: "Nutritional Rock Bottom",
      score5: "Mediocrity on a Plate",
      score6: "Not Great, Not Terrible. Impressed?",
      score7: "Almost Like You Care About Yourself",
      score8: "Well, Aren't You Virtuous Today",
      score9: "Trophy-Worthy, You Smug Health God",
      score10: "Perfect. We're All Very Impressed. Really.",
      dailySummary: "Daily Summary",
      averageScore: "Avg. Score",
      globalError: "An error occurred",
      globalErrorDescription: "Please try again later",
      selectLanguage: "Select Language",
      dietRegular: "Regular",
      dietVegetarian: "Vegetarian",
      dietVegan: "Vegan",
      dietPescatarian: "Pescatarian",
      dietFlexitarian: "Flexitarian",
      dietKeto: "Keto",
      dietLowCarb: "Low Carb",
      dietIntermittentFasting: "Intermittent Fasting",
      dietPaleo: "Paleo",
      dietWestern: "Western",
      dietTypesTitle: "Your Diet Type",
      save: "Save",
    },
  },
};
