export const resources = {
  tr: {
    translation: {
      getStarted: "Başla",
      defineGoals: "Hedeflerini belirleyelim",
      loseWeight: "Kilo Vermek",
      gainMuscle: "Kas Kazanmak",
      eatHealthier: "Sağlıklı Beslenmek",
      getMoreSleep: "Daha Fazla Uyku",
      drinkMoreWater: "Daha Çok Su İçmek",
      reduceStress: "Stresi Azaltmak",
      reduceAlcohol: "Alkolü Azaltmak",
      getMoreActive: "Daha Aktif Olmak",
      proceed: "Devam Et",
      identify: "Kendinizi nasıl tanımlarsınız?",
      male: "Erkek",
      female: "Kadın",
      nonBinary: "Diğer",
      yourAge: "Bize yaşınızı söyleyin",
      whyWeAsk: "Neden yaşınızı soruyoruz?",
      whyWeAskDescription:
        "Yaş, günlük kalori ve makro ihtiyaçlarınızı daha doğru hesaplamamıza yardımcı olur, bu da metabolizmanıza ve hedeflerinize uygun kişiselleştirilmiş beslenme önerileri sağlar.",
      getPhysical: "Fiziksel Özellikler",
      analyzing: "Profiliniz inceleniyor",
      calculating: "Kalori ihtiyacınız hesaplanıyor",
      optimizing: "Makro hedefleriniz belirleniyor",
      height: "Boy",
      weight: "Kilo",
      tabHome: "Bugün",
      tabCook: "Pişir",
      tabChat: "AI Asistan",
      cookImmersiveTitle: "Cooking Badger",
      cookIntroTitle: "Bugün ne pişirmek istiyorsun?",
      cookInputPlaceholder: "Örn. tavuk, köfte, fasulye",
      cookStartPlanning: "Pişir",
      myRecipes: "Tariflerim",
      noRecipesYet: "Henüz tarif yok.",
      noRecipesYetBody: "Pişirmeye başla.",
      cookQuestionTime: "Ne kadar vaktin var?",
      cookQuestionGoal: "Bugünkü hedefin ne?",
      cookQuestionServings: "Kaç porsiyon olsun?",
      cookQuestionMaxCalories: "Porsiyon başına en fazla kaç kalori olsun?",
      cookTime15: "15 dk",
      cookTime30: "30 dk",
      cookTime45: "45+ dk",
      cookGoalHighProtein: "Yüksek protein",
      cookGoalBalanced: "Dengeli",
      cookGoalLowCarb: "Düşük karbonhidrat",
      cookGoalBudgetFriendly: "Ekonomik",
      cookServing1: "1 kişilik",
      cookServing2: "2 kişilik",
      cookServing4: "4+ kişilik",
      cookCalories200: "200 kcal max",
      cookCalories400: "400 kcal max",
      cookCalories600: "600 kcal max",
      cookCalories800: "800 kcal max",
      cookCalories1000: "1000 kcal max",
      cookCaloriesAny: "Fark etmez",
      cookPlanSeed: "Fikir",
      cookPlanTime: "Süre",
      cookPlanGoal: "Hedef",
      cookPlanServings: "Porsiyon",
      cookPlanCalories: "Kalori sınırı",
      cookPlanSummaryTitle: "Plan oluşuyor",
      cookOnboardingTitle: "Elinde ne var?",
      cookOnboardingBody:
        "Bir malzeme ya da fikir yaz. Hedeflerine göre tarif oluşturayım.",
      cookOnboardingCta: "Haydi pişirelim",
      cookAllergenTitle: "Herhangi bir alerjin var mı?",
      cookAllergenBody: "Tarifler buna göre uyarlanacak.",
      cookAllergenNone: "Yok",
      cookAllergenGluten: "Gluten",
      cookAllergenDairy: "Süt Ürünleri",
      cookAllergenEggs: "Yumurta",
      cookAllergenNuts: "Kuruyemiş",
      cookAllergenPeanuts: "Fıstık",
      cookAllergenShellfish: "Kabuklu Deniz Ürünleri",
      cookAllergenFish: "Balık",
      cookAllergenSoy: "Soya",
      cookAllergenSesame: "Susam",
      cookAllergenContinue: "Devam Et",
      cookKitchenTitle: "Mutfak aletlerin neler?",
      cookKitchenBody: "Tarif önerileri buna göre uyarlanacak.",
      cookKitchenOven: "Fırın",
      cookKitchenAirFryer: "Air Fryer",
      cookKitchenStovetop: "Ocak",
      cookKitchenMicrowave: "Mikrodalga",
      cookKitchenBlender: "Blender",
      cookKitchenGrill: "Izgara",
      cookKitchenSlowCooker: "Slow Cooker",
      cookKitchenInstantPot: "Instant Pot",
      cookKitchenContinue: "Devam Et",
      cookQuestionProgress: "Soru {{current}} / {{total}}",
      cookClarifyProgress: "Detay {{current}} / {{total}}",
      cookFollowUpPlaceholder: "Biraz daha detay ver",
      cookContinue: "Devam Et",
      cookRecommended: "Önerilen",
      cookGeneratingCandidates: "Hazırlanıyor",
      cookBuildingRecipe: "Tarif hazırlanıyor",
      cookStartCooking: "Pişirmeye Başla",
      cookModeLabel: "Pişirme modu",
      cookVariationTitle: "Tarifi değiştir",
      cookVariationSubtitle: "Bir varyasyona dokun, tarifi yeniden kurayım",
      cookVariationRefreshing: "Yenileniyor",
      cookMetaPrep: "Hazırlık",
      cookMetaTime: "Süre",
      cookMetaServings: "Porsiyon",
      cookMetaLevel: "Seviye",
      cookDifficultyEasy: "Kolay",
      cookDifficultyMedium: "Orta",
      cookDifficultyHard: "Zor",
      cookIngredientsTitle: "Malzemeler",
      cookStepsTitle: "Adımlar",
      cookTipsTitle: "İpuçları",
      cookTimerLabel: "Zamanlayıcı",
      cookStepProgress: "Adım {{current}} / {{total}}",
      cookPrevious: "Geri",
      cookNextStep: "Sonraki adım",
      cookFinish: "Bitir",
      cookLogMealTitle: "Bu öğün kaydedilsin mi?",
      cookLogMealBody:
        "Bu tarifi pişirdin. Besin değerlerini analiz edip öğün olarak kaydedebilirim.",
      cookLogMealSkip: "Şimdi değil",
      cookLogMealConfirm: "Öğünü kaydet",
      cookLoggingMeal: "Pişirdiğin öğün analiz ediliyor",
      cookCompletedCount: "Tamamlanan adım: {{count}}",
      cookDiscardTitle: "Pişirme kapatılsın mı?",
      cookDiscardBody:
        "Şimdi çıkarsan bu tarif akışı ve seçilen ilerleme kaybolacak.",
      cookDiscardCancel: "Vazgeç",
      cookDiscardConfirm: "Çık",
      cookErrorTitle: "Cook şu an takıldı",
      cookErrorBody: "Tarif planı oluşturulamadı. Tekrar deneyelim.",
      cookTryAgain: "Baştan Başla",
      loggedMeals: "Eklenmiş Öğünler",
      nutritionAssistant: "Beslenme Asistanı",
      startAConversation: "Bir sohbet başlat",
      askQuestion:
        "Beslenme, diyet planları veya yemek önerileri hakkında bir soru sor",
      typeYourMessage: "Mesajınızı yazın",
      settingsTitle: "Ayarlar",
      hi: "Merhaba",
      language: "Dil",
      aiTone: "AI Konuşma Tonu",
      toneHarsh: "Sert (varsayılan)",
      toneFriendly: "Dostça",
      toneFunny: "Eğlenceli",
      toneNerdy: "Bilimsel",
      toneSupportive: "Destekleyici",
      profile: "Profil",
      goals: "Hedefler",
      logout: "Çıkış Yap",
      describeYourMeal: "Öğününüzü tarif edin",
      exampleMeal: "Örnek: Ispanaklı ve domatesli çırpılmış yumurta",
      breakfast: "Kahvaltı",
      lunch: "Öğle Yemeği",
      dinner: "Akşam Yemeği",
      snack: "Atıştırmalık",
      mealType: "Öğün Türü",
      addImage: "Resim Ekle",
      chooseImageSource: "Resim Kaynağını Seçin",
      camera: "Kamera",
      cameraPermissionRequired: "Yemek taramak icin kamera izni gerekiyor.",
      gallery: "Galeri",
      cancel: "İptal",
      carbs: "Karb.",
      proteins: "Protein",
      fats: "Yağ",
      calories: "Kalori",
      analyzeMeal: "Öğünü Analiz Et",
      confirmPortions: "Porsiyonları onayla",
      confirmPortionsDescription:
        "Kaloriyi en çok etkileyen miktarları düzelt.",
      quickDetails: "Hızlı detaylar",
      adjustPortion: "Miktarı düzelt",
      minorIngredient: "Küçük etki",
      checkingPortions: "Porsiyonlar tahmin ediliyor",
      howWasMyLastMeal: "Son öğünüm nasıldı?",
      brutallyHonestFeedback: "Bana acımasız bir geri bildirim ver",
      howHealthyIsMyBmi: "BMI'ım ne kadar sağlıklı?",
      whatShouldIEatForDinner: "Akşam yemeğinde ne yemeliyim?",
      amIGettingEnoughProtein: "Yeterli protein alıyor muyum?",
      suggestAHealthySnack: "Sağlıklı bir atıştırmalık öner",
      insights: "Tavsiyeler",
      mealAnalysis: "Yemek Analizi",
      nutritionScore: "Beslenme Puanı",
      macronutrients: "Makro Besinler",
      cal: "kal",
      delete: "Sil",
      edit: "Düzenle",
      scanAnother: "Başka Tara",
      deleteConfirmation: "Silme Onayı",
      deleteItemConfirmationMessage:
        "Bu öğeyi silmek istediğinizden emin misiniz?",
      error: "Hata",
      deleteFailed: "Silme işlemi başarısız oldu",
      score1: "Beslenme değil bu, biyolojik sabotaj.",
      score2: "Vücudun resmen istifa etmeye hazırlanıyor.",
      score3: "Kendini mi cezalandırıyorsun?",
      score4: "Vasat bile diyemiyorum.",
      score5: "Vasatın da alt sınırındasın.",
      score6: "Ne iyi ne kötü... İşte öyle bir şey.",
      score7: "Kendine biraz değer vermeye başlamışsın sanki.",
      score8: "Bugün sağlıklı kararlar krallığına adım attın.",
      score9: "Vücut şükrediyor, melekler alkışlıyor.",
      score10: "Mükemmel. Herkes seni konuşuyor. Bravo gerçekten.",
      // Friendly tone score explanations (Turkish)
      score1_friendly:
        "Bu öğün biraz sevgiye ihtiyaç duyuyor. Daha iyi seçenekler bulalım!",
      score2_friendly: "Geliştirilecek alan var. Yapabilirsin!",
      score3_friendly: "Zor bir tercih, ama yarın yeni bir gün.",
      score4_friendly: "En iyisi değil, ama her öğün bir öğrenme fırsatı.",
      score5_friendly:
        "Yarı yoldasın! Küçük değişiklikler büyük fark yaratabilir.",
      score6_friendly: "İyi bir çaba. Üzerine inşa etmeye devam et!",
      score7_friendly: "Güzel iş! İyi ilerleme kaydediyorsun.",
      score8_friendly: "Harika tercih! Vücudun sana teşekkür ediyor.",
      score9_friendly: "Mükemmel! Gerçekten başarıyorsun.",
      score10_friendly:
        "Olağanüstü! Sağlıklı beslenme tam olarak böyle görünür.",
      // Funny tone score explanations (Turkish)
      score1_funny: "Miden bile şikayet dilekçesi yazıyor.",
      score2_funny: "Diyetisyenin bir yerlerde bayıldı.",
      score3_funny:
        "Cesur strateji. Bakalım işe yarayacak mı. (Spoiler: hayır)",
      score4_funny: "Bu bir öğün mü yoksa yardım çığlığı mı?",
      score5_funny: "Eh işte. Yemek formunda bir pazartesi sabahı.",
      score6_funny:
        "Kabul edilebilir. Havaalanı yemeği gibi, ama biraz daha iyi.",
      score7_funny: "Bak sen! Sebzelerle yetişkin gibi davranıyorsun!",
      score8_funny: "Sen kimsin ve eski sen nerede?",
      score9_funny: "Vücudun şu an mini bir kutlama yapıyor.",
      score10_funny: "Şef öpücüğü! Gelecekteki sen sana beşlik çakıyor.",
      // Nerdy tone score explanations (Turkish)
      score1_nerdy:
        "Makro profil kritik seviyede. Acil beslenme kalibrasyonu önerilir.",
      score2_nerdy:
        "Besin yoğunluğu: minimum. Optimizasyon şiddetle tavsiye edilir.",
      score3_nerdy: "Bu örnekte suboptimal besin oranları tespit edildi.",
      score4_nerdy: "Veriler, baz çizgisinin altında besin değeri gösteriyor.",
      score5_nerdy: "Beslenme metrikleri medyan eşiğinde.",
      score6_nerdy:
        "Kabul edilebilir makro dengesi, optimizasyon alanı mevcut.",
      score7_nerdy: "İyi besin-kalori oranı gözlemlendi.",
      score8_nerdy: "Güçlü mikro besin profili. İyi kalibre edilmiş öğün.",
      score9_nerdy: "Neredeyse optimal makro dağılımı. Mükemmel veri noktası.",
      score10_nerdy:
        "Zirve beslenme verimliliği sağlandı. Ders kitabı uygulaması.",
      // Supportive tone score explanations (Turkish)
      score1_supportive:
        "Her adım ilerleme demek. Bir sonraki öğünü daha iyi planlayalım.",
      score2_supportive: "Sorun değil. Önemli olan takip edip öğrenmen.",
      score3_supportive: "Farkındasın ve bu değişimin ilk adımı.",
      score4_supportive: "İdeal değil, ama dikkat ediyorsun. Bu önemli.",
      score5_supportive: "Doğru yoldasın. Devam et!",
      score6_supportive: "Sağlam çaba! Her öğün gelişme şansı.",
      score7_supportive: "İyi gidiyorsun! Bu tercihle gurur duy.",
      score8_supportive: "Harika! Bu gerçek bir sağlık taahhüdü gösteriyor.",
      score9_supportive: "Müthiş iş! Bundan dolayı harika hissetmelisin.",
      score10_supportive: "İnanılmaz! Kendine harika bakıyorsun.",
      globalError: "Bir hata oluştu",
      selectLanguage: "Dil Seçin",
      dietRegular: "Standart",
      dietVegetarian: "Vejetaryen",
      dietVegan: "Vegan",
      dietPescatarian: "Pesketaryen",
      dietFlexitarian: "Esnek Vegan",
      dietKeto: "Ketojenik",
      dietLowCarb: "Düşük Karbonhidrat",
      dietIntermittentFasting: "Aralıklı Oruç",
      dietPaleo: "Paleo",
      dietWestern: "Batı Tipi",
      dietTypesTitle: "Beslenme Düzenin",
      save: "Kaydet",
      logoutConfirmation: "Çıkış Yap",
      logoutConfirmationMessage: "Çıkış yapmak istediğinizden emin misiniz?",
      deleteAccountConfirmation: "Hesabı Sil",
      deleteAccountConfirmationMessage:
        "Hesabınızı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
      theme: "Tema",
      themePickerTitle: "Tema Seç",
      themeOnyx: "Onyx",
      themeMidnightGold: "Gece Altını",
      themeNoirRose: "Noir Gül",
      themeDeepOcean: "Derin Okyanus",
      themeVioletDusk: "Mor Alacakaranlık",
      themeIvory: "Fildişi",
      welcomeExplanation:
        "Öğünlerini takip et, hedefine odaklan. Gerisi kendiliğinden gelir.",
      welcomeHeadline1Pre: "Akıllı",
      welcomeHeadline1Accent: "ye.",
      welcomeHeadline2: "Formda kal.",
      featureCalorieTracking: "Kalori takibi",
      featureAiSuggestions: "Yapay zeka önerileri",
      featureRecipeGenerator: "Tarif üretici",
      existingUser: "Zaten hesabın var mı?",
      login: "Giriş Yap",
      signUpTitle: "Fit Badger'a Katıl!",
      signUpSubtitle: "Öğünleri takip et ve hedeflerine ulaş.",
      signUpWithGoogle: "Google ile kayıt ol",
      signUpWithApple: "Apple ile kayıt ol",
      signUpWithEmail: "E-posta ile kayıt ol",
      email: "E-posta",
      password: "Şifre",
      confirmPassword: "Şifreyi Onayla",
      enterEmail: "E-posta adresinizi girin",
      enterPassword: "Şifrenizi girin",
      confirmYourPassword: "Şifrenizi onaylayın",
      signUp: "Kayıt Ol",
      alreadyHaveAccount: "Zaten hesabın var mı?",
      logIn: "Giriş Yap",
      termsAgreement: "Devam ederek",
      termsOfService: "Kullanım Şartları",
      and: "ve",
      privacyPolicy: "Gizlilik Politikası",
      termsAgreementEnd: "kabul etmiş olursunuz.",
      invalidEmail: "Geçersiz e-posta adresi",
      passwordsDoNotMatch: "Şifreler eşleşmiyor",
      loginTitle: "Tekrar Hoş Geldin!",
      loginSubtitle: "Hesabına giriş yap.",
      loginWithGoogle: "Google ile giriş yap",
      loginWithApple: "Apple ile giriş yap",
      loginWithEmail: "E-posta ile giriş yap",
      noAccountYet: "Hesabın yok mu?",
      globalErrorMessage: "Lütfen daha sonra tekrar deneyin",
      signUpBanner: "Kayıt olarak profilini tamamla.",
      nutritionGoals: "Beslenme Hedefleri",
      dailyGoal: "GÜNLÜK HEDEF",
      caloriesLeft: "Kalori kaldı",
      caloriesOver: "Kalori aşıldı",
      caloriesConsumed: "Alınan Kalori",
      proteinLeft: "Protein kaldı",
      proteinOver: "Protein aşıldı",
      carbsLeft: "Karb. kaldı",
      carbsOver: "Karb. aşıldı",
      fatsLeft: "Yağ kaldı",
      fatsOver: "Yağ aşıldı",
      proteinConsumed: "Protein",
      carbsConsumed: "Karb.",
      fatsConsumed: "Yağ",
      nutritionDisplayToggleAccessibility: "Kalan ile tüketilen arasında geçiş",
      nutritionDisplayModeConsumed: "Tüketilen",
      nutritionDisplayModeRemaining: "Kalan",
      nutritionDisplayTapToSwitchView: "Görünümü değiştirmek için dokun",
      tapToAddMeal: "Öğün eklemek için dokun",
      analyzingMeal: "Öğününüz analiz ediliyor",
      carouselMessage3: "Kişiselleştirilmiş planınız hazırlanıyor.",
      tabSettings: "Ayarlar",
      // Notification strings
      notifications: "Bildirimler",
      enableNotifications: "Bildirimleri Etkinleştir",
      mealReminders: "Öğün Hatırlatıcıları",
      mealTimeTitle: "Öğün Saatleri",
      mealTimeDescription:
        "Öğün hatırlatıcıları almak için yaklaşık öğün saatlerinizi ayarlayın.",
      reminderTime: "Hatırlatma saati",
      breakfastReminder: "Kahvaltı Zamanı! 🍳",
      lunchReminder: "Öğle Yemeği Zamanı! 🥗",
      dinnerReminder: "Akşam Yemeği Zamanı! 🍽️",
      mealReminderBody: "Öğününüzü kaydetmeyi unutmayın!",
      notificationPermissionDenied: "Bildirim İzni Reddedildi",
      notificationPermissionDeniedMessage:
        "Lütfen hatırlatıcılar için ayarlardan bildirim iznini etkinleştirin.",
    },
  },

  en: {
    translation: {
      getStarted: "Get Started",
      defineGoals: "First, let's define your goals",
      loseWeight: "Lose Weight",
      gainMuscle: "Gain Muscle",
      eatHealthier: "Eat Healthier",
      getMoreSleep: "Get More Sleep",
      drinkMoreWater: "Drink More Water",
      reduceStress: "Reduce Stress",
      reduceAlcohol: "Reduce Alcohol",
      getMoreActive: "Get More Active",
      proceed: "Proceed",
      identify: "How do you identify?",
      male: "Male",
      female: "Female",
      nonBinary: "Non-binary",
      yourAge: "Tell us your age",
      whyWeAsk: "Why do we ask your age?",
      whyWeAskDescription:
        "Age helps us calculate your daily calorie and macro needs more accurately, so recommendations actually fit your metabolism and goals.",
      getPhysical: "Physical Details",
      analyzing: "Scanning your data",
      calculating: "Crunching your numbers",
      optimizing: "Locking in your macros",
      height: "Height",
      weight: "Weight",
      tabHome: "Today",
      tabCook: "Cook",
      tabChat: "AI Coach",
      cookImmersiveTitle: "Cooking Badger",
      cookIntroTitle: "What are you thinking of cooking?",
      cookInputPlaceholder: "Ex. chicken, quick pasta, lentils",
      cookStartPlanning: "Cook",
      myRecipes: "My Recipes",
      noRecipesYet: "No recipes yet.",
      noRecipesYetBody: "Start cooking.",
      cookQuestionTime: "How much time do you have?",
      cookQuestionGoal: "What's your goal today?",
      cookQuestionServings: "How many servings?",
      cookQuestionMaxCalories: "What's the max calories per serving?",
      cookTime15: "15 min",
      cookTime30: "30 min",
      cookTime45: "45+ min",
      cookGoalHighProtein: "High Protein",
      cookGoalBalanced: "Balanced",
      cookGoalLowCarb: "Low Carb",
      cookGoalBudgetFriendly: "Budget Friendly",
      cookServing1: "1 serving",
      cookServing2: "2 servings",
      cookServing4: "4+ servings",
      cookCalories200: "200 kcal max",
      cookCalories400: "400 kcal max",
      cookCalories600: "600 kcal max",
      cookCalories800: "800 kcal max",
      cookCalories1000: "1000 kcal max",
      cookCaloriesAny: "No limit",
      cookPlanSeed: "Idea",
      cookPlanTime: "Time",
      cookPlanGoal: "Goal",
      cookPlanServings: "Servings",
      cookPlanCalories: "Calorie cap",
      cookPlanSummaryTitle: "Building your plan",
      cookOnboardingTitle: "What are you working with?",
      cookOnboardingBody:
        "Tell me an ingredient or an idea. I'll build a recipe around your goals.",
      cookOnboardingCta: "Let's cook",
      cookAllergenTitle: "Any allergens?",
      cookAllergenBody: "Recipes will be adapted accordingly.",
      cookAllergenNone: "None",
      cookAllergenGluten: "Gluten",
      cookAllergenDairy: "Dairy",
      cookAllergenEggs: "Eggs",
      cookAllergenNuts: "Tree Nuts",
      cookAllergenPeanuts: "Peanuts",
      cookAllergenShellfish: "Shellfish",
      cookAllergenFish: "Fish",
      cookAllergenSoy: "Soy",
      cookAllergenSesame: "Sesame",
      cookAllergenContinue: "Continue",
      cookKitchenTitle: "What's in your kitchen?",
      cookKitchenBody: "Recipe suggestions will be adapted accordingly.",
      cookKitchenOven: "Oven",
      cookKitchenAirFryer: "Air Fryer",
      cookKitchenStovetop: "Stovetop",
      cookKitchenMicrowave: "Microwave",
      cookKitchenBlender: "Blender",
      cookKitchenGrill: "Grill",
      cookKitchenSlowCooker: "Slow Cooker",
      cookKitchenInstantPot: "Instant Pot",
      cookKitchenContinue: "Continue",
      cookQuestionProgress: "Question {{current}} / {{total}}",
      cookClarifyProgress: "Detail {{current}} / {{total}}",
      cookFollowUpPlaceholder: "Add one more detail",
      cookContinue: "Continue",
      cookRecommended: "Recommended",
      cookGeneratingCandidates: "Preparing",
      cookBuildingRecipe: "Building recipe",
      cookStartCooking: "Start Cooking",
      cookModeLabel: "Cook mode",
      cookVariationTitle: "Change this recipe",
      cookVariationSubtitle: "Tap a variation and I will rebuild it",
      cookVariationRefreshing: "Refreshing",
      cookMetaPrep: "Prep",
      cookMetaTime: "Time",
      cookMetaServings: "Servings",
      cookMetaLevel: "Level",
      cookDifficultyEasy: "Easy",
      cookDifficultyMedium: "Medium",
      cookDifficultyHard: "Hard",
      cookIngredientsTitle: "Ingredients",
      cookStepsTitle: "Steps",
      cookTipsTitle: "Tips",
      cookTimerLabel: "Timer",
      cookStepProgress: "Step {{current}} of {{total}}",
      cookPrevious: "Previous",
      cookNextStep: "Next step",
      cookFinish: "Finish",
      cookLogMealTitle: "Log this meal?",
      cookLogMealBody:
        "You finished cooking this recipe. I can analyze it and log it as a meal.",
      cookLogMealSkip: "Not now",
      cookLogMealConfirm: "Log meal",
      cookLoggingMeal: "Analyzing your cooked meal",
      cookCompletedCount: "Completed steps: {{count}}",
      cookDiscardTitle: "Leave cooking?",
      cookDiscardBody:
        "If you exit now, this recipe flow and your current progress will be discarded.",
      cookDiscardCancel: "Cancel",
      cookDiscardConfirm: "Leave",
      cookErrorTitle: "Cook hit a snag",
      cookErrorBody:
        "I couldn't build that recipe plan right now. Let's try again.",
      cookTryAgain: "Start Over",
      loggedMeals: "Logged Meals",
      nutritionAssistant: "Nutrition Coach",
      startAConversation: "Start a conversation",
      askQuestion:
        "Ask a question about nutrition, diet plans, or meal suggestions",
      typeYourMessage: "Type your message",
      settingsTitle: "Settings",
      hi: "Hi",
      language: "Language",
      aiTone: "AI speaking tone",
      toneHarsh: "Harsh (default)",
      toneFriendly: "Friendly",
      toneFunny: "Funny",
      toneNerdy: "Nerdy",
      toneSupportive: "Supportive",
      profile: "Profile",
      goals: "Goals",
      logout: "Log Out",
      describeYourMeal: "Describe your meal",
      exampleMeal: "Example: Scrambled eggs with spinach and tomatoes",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
      mealType: "Meal Type",
      addImage: "Add Image",
      chooseImageSource: "Choose Image Source",
      camera: "Camera",
      cameraPermissionRequired: "Camera permission is required to scan a meal.",
      gallery: "Gallery",
      cancel: "Cancel",
      carbs: "Carbs",
      proteins: "Proteins",
      fats: "Fats",
      calories: "Calories",
      analyzeMeal: "Analyze Meal",
      confirmPortions: "Confirm portions",
      confirmPortionsDescription:
        "Adjust the amounts that affect calories most.",
      quickDetails: "Quick details",
      adjustPortion: "Adjust portion",
      minorIngredient: "Small impact",
      checkingPortions: "Estimating portions",
      howWasMyLastMeal: "How was my last meal?",
      brutallyHonestFeedback: "Give me brutally honest feedback",
      howHealthyIsMyBmi: "How healthy is my BMI?",
      whatShouldIEatForDinner: "What should I eat for dinner?",
      amIGettingEnoughProtein: "Am I getting enough protein?",
      suggestAHealthySnack: "Suggest a healthy snack",
      insights: "Insights",
      mealAnalysis: "Meal Analysis",
      nutritionScore: "Nutrition Score",
      macronutrients: "Macronutrients",
      cal: "cal",
      delete: "Delete",
      edit: "Edit",
      scanAnother: "Scan Another",
      deleteConfirmation: "Delete Confirmation",
      deleteItemConfirmationMessage:
        "Are you sure you want to delete this item?",
      error: "Error",
      deleteFailed: "Delete failed",
      score1: "This isn't nutrition. It's sabotage.",
      score2: "Your body is drafting a resignation letter.",
      score3: "Punishing yourself again?",
      score4: "Calling this food is generous.",
      score5: "Below average. Impressively so.",
      score6: "Not great. Not terrible.",
      score7: "Looks like you almost care.",
      score8: "Good choices today. Shocking.",
      score9: "Your body approves. Rare event.",
      score10: "Perfect. No notes.",
      // Friendly tone score explanations
      score1_friendly: "This meal needs some love. Let's find better options!",
      score2_friendly: "Room for improvement here. You've got this!",
      score3_friendly: "A challenging choice, but tomorrow is a new day.",
      score4_friendly: "Not your best, but every meal is a learning moment.",
      score5_friendly: "Halfway there! Small tweaks can make a big difference.",
      score6_friendly: "A decent effort. Keep building on it!",
      score7_friendly: "Nice work! You're making good progress.",
      score8_friendly: "Great choice! Your body thanks you.",
      score9_friendly: "Excellent! You're really nailing this.",
      score10_friendly: "Outstanding! This is exactly what healthy looks like.",
      // Funny tone score explanations
      score1_funny: "Even your stomach is filing a complaint.",
      score2_funny: "Your nutritionist just fainted somewhere.",
      score3_funny: "Bold strategy. Let's see if it pays off. (Spoiler: no)",
      score4_funny: "Is this a meal or a cry for help?",
      score5_funny: "Meh. Like a Monday morning in food form.",
      score6_funny: "Acceptable. Like airport food, but slightly better.",
      score7_funny: "Look at you, adulting with vegetables!",
      score8_funny: "Who are you and what did you do with the old you?",
      score9_funny: "Your body is throwing a tiny party right now.",
      score10_funny: "Chef's kiss! Your future self is high-fiving you.",
      // Nerdy tone score explanations
      score1_nerdy:
        "Macro profile critical. Immediate dietary recalibration advised.",
      score2_nerdy:
        "Nutrient density: minimal. Optimization strongly recommended.",
      score3_nerdy: "Suboptimal nutrient ratios detected in this sample.",
      score4_nerdy: "Data suggests below-baseline nutritional value.",
      score5_nerdy: "Nutritional metrics at median threshold.",
      score6_nerdy: "Acceptable macro balance with room for optimization.",
      score7_nerdy: "Good nutrient-to-calorie ratio observed.",
      score8_nerdy: "Strong micronutrient profile. Well-calibrated meal.",
      score9_nerdy: "Near-optimal macro distribution. Excellent data point.",
      score10_nerdy:
        "Peak nutritional efficiency achieved. Textbook execution.",
      // Supportive tone score explanations
      score1_supportive:
        "Every step is progress. Let's plan a better next meal.",
      score2_supportive:
        "It's okay. What matters is you're tracking and learning.",
      score3_supportive: "You're aware, and that's the first step to change.",
      score4_supportive: "Not ideal, but you're paying attention. That counts.",
      score5_supportive: "You're on the right path. Keep going!",
      score6_supportive: "Solid effort! Each meal is a chance to improve.",
      score7_supportive: "You're doing well! Be proud of this choice.",
      score8_supportive:
        "Wonderful! This shows real commitment to your health.",
      score9_supportive: "Amazing work! You should feel great about this.",
      score10_supportive: "Incredible! You're taking amazing care of yourself.",
      globalError: "An error occurred",
      selectLanguage: "Select Language",
      dietRegular: "Regular",
      dietVegetarian: "Vegetarian",
      dietVegan: "Vegan",
      dietPescatarian: "Pescatarian",
      dietFlexitarian: "Flexitarian",
      dietKeto: "Keto",
      dietLowCarb: "Low Carb",
      dietIntermittentFasting: "Intermittent Fasting",
      dietPaleo: "Paleo",
      dietWestern: "Western",
      dietTypesTitle: "Your Diet Type",
      save: "Save",
      logoutConfirmation: "Log Out",
      logoutConfirmationMessage: "Are you sure you want to log out?",
      deleteAccountConfirmation: "Delete Account",
      deleteAccountConfirmationMessage:
        "Are you sure you want to delete your account? This action is irreversible.",
      theme: "Theme",
      themePickerTitle: "Choose Theme",
      themeOnyx: "Onyx",
      themeMidnightGold: "Midnight Gold",
      themeNoirRose: "Noir Rose",
      themeDeepOcean: "Deep Ocean",
      themeVioletDusk: "Violet Dusk",
      themeIvory: "Ivory",
      welcomeExplanation:
        "Track your meals, lock in your goal. The rest takes care of itself.",
      welcomeHeadline1Pre: "Eat",
      welcomeHeadline1Accent: "smart.",
      welcomeHeadline2: "Stay lean.",
      featureCalorieTracking: "Calorie tracking",
      featureAiSuggestions: "AI suggestions",
      featureRecipeGenerator: "Recipe generator",
      existingUser: "Already have an account?",
      login: "Log In",
      signUpTitle: "Join Fit Badger!",
      signUpSubtitle: "Track meals and achieve your goals.",
      signUpWithGoogle: "Sign up with Google",
      signUpWithApple: "Sign up with Apple",
      signUpWithEmail: "Sign up with Email",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      enterEmail: "Enter your email",
      enterPassword: "Enter your password",
      confirmYourPassword: "Confirm your password",
      signUp: "Sign Up",
      alreadyHaveAccount: "Already have an account?",
      logIn: "Log In",
      termsAgreement: "By continuing, you agree to our",
      termsOfService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      termsAgreementEnd: ".",
      invalidEmail: "Invalid email address",
      passwordsDoNotMatch: "Passwords do not match",
      loginTitle: "Welcome Back!",
      loginSubtitle: "Log in to your account.",
      loginWithGoogle: "Log in with Google",
      loginWithApple: "Log in with Apple",
      loginWithEmail: "Log in with Email",
      noAccountYet: "Don't have an account?",
      globalErrorMessage: "Please try again later",
      signUpBanner: "Sign up to complete your profile.",
      nutritionGoals: "Nutrition Goals",
      dailyGoal: "DAILY GOAL",
      caloriesLeft: "Calories left",
      caloriesOver: "Calories over",
      caloriesConsumed: "Calories consumed",
      proteinLeft: "Protein left",
      proteinOver: "Protein over",
      carbsLeft: "Carbs left",
      carbsOver: "Carbs over",
      fatsLeft: "Fats left",
      fatsOver: "Fats over",
      proteinConsumed: "Protein consumed",
      carbsConsumed: "Carbs consumed",
      fatsConsumed: "Fats consumed",
      nutritionDisplayToggleAccessibility:
        "Switch between consumed and remaining",
      nutritionDisplayModeConsumed: "Consumed",
      nutritionDisplayModeRemaining: "Remaining",
      nutritionDisplayTapToSwitchView: "Tap to switch view",
      tapToAddMeal: "Tap to add a meal",
      analyzingMeal: "Analyzing your meal",
      carouselMessage3: "Your personalized plan is being prepared.",
      tabSettings: "Settings",
      // Notification strings
      notifications: "Notifications",
      enableNotifications: "Enable Notifications",
      mealReminders: "Meal Reminders",
      mealTimeTitle: "Set Meal Times",
      mealTimeDescription:
        "Set your approximate meal times to receive meal reminders.",
      reminderTime: "Reminder time",
      breakfastReminder: "Breakfast Time! 🍳",
      lunchReminder: "Lunch Time! 🥗",
      dinnerReminder: "Dinner Time! 🍽️",
      mealReminderBody: "Don't forget to log your meal!",
      notificationPermissionDenied: "Notification Permission Denied",
      notificationPermissionDeniedMessage:
        "Please enable notification permission in settings for reminders.",
    },
  },
};
